Update for 3.2, added -a flag
Added -a flag for apk-tools-static package. This tends to change per
release so best not to hardcode it

diff --git a/install b/install
--- a/install
+++ b/install
@@ -19,13 +19,14 @@ cat <<EOF
 Install and modify Alpine in a given directory in a given directory using a given mirror
 
 Usage:
-  $0 -r <RELEASE> -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
+  $0 -r <RELEASE> -a <APK_TOOLS> -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
 
 Example:
-  $0 -r 3.1 -d /data/chroot -m http://mirrors.gigenet.com/alpinelinux/ -i lx-alpine -p "Alpine LX Brand" -D "Alpine 3.1.3 64-bit lx-brand image." -u https://docs.joyent.com/images/lx-brand-beta
+  $0 -r 3.1 -a apk-tools-static-2.6.1-r0.apk -d /data/alpine -m http://mirrors.gigenet.com/alpinelinux/ -i alpine-3 -p "Alpine Linux" -D "Alpine 3.1.3 64-bit lx-brand image." -u https://docs.joyent.com/images/lx-brand-beta
 
 OPTIONS:
-  -r The desired release (e.g "3.1")
+  -r The desired release (e.g "3.2")
+  -a The required apk-tools-static package (e.g. apk-tools-static-2.6.1-r0.apk)
   -d A path to the install directory
   -m A URL for the desired archive mirror
   -i The name of the image. This is used for naming the tarball. 
@@ -39,7 +40,7 @@ EOF
 }
 
 RELEASE=
-APK_TOOLS=apk-tools-static-2.5.0_rc1-r1.apk
+APK_TOOLS=
 INSTALL_DIR=
 MIRROR=
 IMAGE_NAME=
@@ -47,7 +48,7 @@ NAME=
 DESC=
 DOCS=
 
-while getopts "hr:d:m:i:p:D:u:" OPTION
+while getopts "hr:a:d:m:i:p:D:u:" OPTION
 do
   case $OPTION in
     h)
@@ -56,6 +57,9 @@ do
       ;;
     r)
       RELEASE=${OPTARG}
+      ;;
+    a)
+      APK_TOOLS=${OPTARG}
       ;;
     d)
       INSTALL_DIR=${OPTARG%/}
@@ -89,6 +93,11 @@ fi
 
 if [[ -z ${RELEASE} ]]; then
   echo "Error: missing release (-r) value"
+  exit 1
+fi
+
+if [[ -z ${APK_TOOLS} ]]; then
+  echo "Error: missing apk-tools-static package (-a) value"
   exit 1
 fi
 
